apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
 replicas: 3
 template:
    metadata:
      name: nginx  
    spec:
     containers:
     - name: nginx
       image: nginx
       ports:
       - containerPort: 80